---
all:
  hosts:
    rosie:
      hostname: rosie
      ansible_host: "{{ rosie_ip }}"
      discord_bot_token: "{{ rosie_bot_token }}"
      discord_allowed_users: "{{ rosie_discord_allowed_users }}"
      discord_home_channel: "{{ rosie_discord_home_channel }}"
      honcho_base_url: "{{ rosie_honcho_base_url }}"
      honcho_api_key: "{{ rosie_honcho_api_key }}"
      honcho_db_password: "{{ rosie_honcho_db_password }}"
      home_assistant_url: "{{ rosie_home_assistant_url }}"
      home_assistant_token: "{{ rosie_home_assistant_token }}"
      mattermost_url: "{{ rosie_mattermost_url }}"
      mattermost_token: "{{ rosie_mattermost_token }}"
      mattermost_allowed_users: "{{ rosie_mattermost_allowed_users }}"
      custom_dns_server: "{{ rosie_custom_dns_server }}"
      custom_dns_domain: "{{ rosie_custom_dns_domain }}"
      custom_ca_certificate_path: "{{ rosie_custom_ca_certificate_path }}"
      hermes_model: "openai/gpt-5.4-mini"
      hermes_inference_provider: "nous"
    athena:
      hostname: athena
      ansible_host: "{{ athena_ip }}"
      discord_bot_token: "{{ athena_bot_token }}"
      git_user_name: "{{ default_git_user_name }}"
      git_user_email: "{{ default_git_user_email }}"
      discord_allowed_users: "{{ athena_discord_allowed_users }}"
      discord_home_channel: "{{ athena_discord_home_channel }}"
      honcho_base_url: "{{ athena_honcho_base_url }}"
      honcho_api_key: "{{ athena_honcho_api_key }}"
      honcho_db_password: "{{ athena_honcho_db_password }}"
      github_token: "{{ athena_github_token }}"
      mattermost_url: "{{ athena_mattermost_url }}"
      mattermost_token: "{{ athena_mattermost_token }}"
      mattermost_allowed_users: "{{ athena_mattermost_allowed_users }}"
      hermes_model: "openai/gpt-5.4"
      hermes_inference_provider: "nous"
