---
all:
  children:
    openclaw_servers:
      hosts:
        jarvis:
          ansible_host: "{{ jarvis_ip }}"
          ansible_python_interpreter: /usr/bin/python3
          openclaw_name: jarvis
          github_pat: "{{ github_pat_jarvis }}"
