---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: true
  become_user: openclaw
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ openclaw_uid.stdout }}
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{ openclaw_uid.stdout }}/bus

- name: Restart openclaw
  ansible.builtin.systemd:
    name: openclaw-gateway
    state: restarted
    scope: user
  become: true
  become_user: openclaw
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ openclaw_uid.stdout }}
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{ openclaw_uid.stdout }}/bus
