---
- name: Deploy Agent servers
  hosts: CHANGEME_HOST_NAME
  become: true
  vars_files:
    - vault.yml
  roles:
    - tjmaynes.agents.base
    - tjmaynes.agents.docker
    - tjmaynes.agents.hermes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    agent_name: "hermes"
    agent_firecrawl_api_key: "{{ default_firecrawl_api_key }}"
    agent_firecrawl_base_url: "{{ default_firecrawl_base_url }}"
    docker_honcho_enabled: true
