---
all:
  hosts:
    CHANGEME_HOST_NAME:
      hostname: CHANGEME_HOST_NAME
      ansible_host: "{{ CHANGEME_HOST_NAME_ip }}"
      agent_discord_bot_token: "{{ CHANGEME_HOST_NAME_bot_token }}"
      agent_discord_allowed_users: "{{ CHANGEME_HOST_NAME_discord_allowed_users }}"
      agent_discord_home_channel: "{{ CHANGEME_HOST_NAME_discord_home_channel }}"
      agent_honcho_base_url: "{{ CHANGEME_HOST_NAME_honcho_base_url }}"
      agent_honcho_api_key: "{{ CHANGEME_HOST_NAME_honcho_api_key }}"
      docker_honcho_db_password: "{{ CHANGEME_HOST_NAME_honcho_db_password }}"
      agent_model: "openai/gpt-5.4-mini"
      agent_inference_provider: "nous"
